### Importing Tensorflow

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.19.0'

### Creating a Scaler

In [4]:
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

### Creating a Vector

In [5]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant([
    [10, 19],
    [20, 21]
])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 19],
       [20, 21]])>

In [8]:
matrix.ndim

2

### Creating a Tensor

In [12]:
tensor = tf.constant([
    [
        [10, 11, 12],
        [90, 21, 45]
    ],
    [
        [10, 78, 70],
        [45, 67, 78],
    ]
])

tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[10, 11, 12],
        [90, 21, 45]],

       [[10, 78, 70],
        [45, 67, 78]]])>

In [10]:
tensor.ndim

3

### Creating Variable Tensors

In [3]:
change_tensor = tf.Variable([10, 7])

change_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>

In [4]:
change_tensor[1].assign(8)

change_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  8])>

### Creating Random Tensors

In [8]:
random = tf.random.Generator.from_seed(42)

random_1 = random.normal(shape=(2, 2))
random_1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

### Shuffle Tensors

In [9]:
t1 = tf.Variable([[10, 7],
                  [8, 9],
                  [1, 4]])


tf.random.shuffle(t1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 8,  9],
       [ 1,  4],
       [10,  7]])>

### Creating a tensor of ones

In [2]:
t1 = tf.ones(shape=(3, 3))

t1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

### Creating a tensor of zeros

In [3]:
t1 = tf.zeros(shape=(3, 3))

t1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### Creating tensor from numpy array

In [4]:
import numpy as np

In [6]:
arr1 = np.arange(1, 25, 1)

matrix_1 = tf.constant(arr1)
matrix_1

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

### Expanding/Increasing dimension of a tensor

In [7]:
rank_2_tensor = tf.ones(shape=(2, 2))

In [8]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [19]:
tf.expand_dims(rank_2_tensor, axis=2)

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[1.],
        [1.]],

       [[1.],
        [1.]]], dtype=float32)>