### Importing Tensorflow

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.19.0'

### Creating a Scaler

In [4]:
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

### Creating a Vector

In [5]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant([
    [10, 19],
    [20, 21]
])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 19],
       [20, 21]])>

In [8]:
matrix.ndim

2

### Creating a Tensor

In [12]:
tensor = tf.constant([
    [
        [10, 11, 12],
        [90, 21, 45]
    ],
    [
        [10, 78, 70],
        [45, 67, 78],
    ]
])

tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[10, 11, 12],
        [90, 21, 45]],

       [[10, 78, 70],
        [45, 67, 78]]])>

In [10]:
tensor.ndim

3